import { addDays, addMonths, format } from "date-fns";
import type { AttendanceEntry, Member } from "../types";
import { calculateBmi } from "./utils";

const today = new Date();

export const sampleMembers: Member[] = [
  {
    id: "member-001",
    regNo: "FW-001",
    name: "Arun Prakash",
    phone: "9876543210",
    age: 28,
    gender: "Male",
    joinDate: format(addMonths(today, -5), "yyyy-MM-dd"),
    weightKg: 82,
    heightCm: 176,
    bmi: calculateBmi(82, 176),
    goal: "Muscle Gain",
    healthProblem: "Mild shoulder stiffness",
    specialInstruction: "Avoid heavy overhead press until mobility improves.",
    warmupExercises: "Band pull-aparts, shoulder circles, treadmill walk",
    flexibilityTraining: "Chest opener, lat stretch",
    cardioTraining: "Incline walk 12 minutes",
    planType: "3 Months",
    membershipStart: format(addMonths(today, -2), "yyyy-MM-dd"),
    membershipDue: format(addDays(today, 3), "yyyy-MM-dd"),
    feesAmount: 4500,
    paymentStatus: "Paid",
    status: "Active",
    smsSent3days: false,
    trainingType: "General",
    address: "",
    partialPaidAmount: 4500,
    balanceAmount: 0,
    createdAt: addMonths(today, -5).toISOString(),
    updatedAt: today.toISOString(),
  },
  {
    id: "member-002",
    regNo: "FW-002",
    name: "Divya Kumar",
    phone: "9123456780",
    age: 34,
    gender: "Female",
    joinDate: format(addMonths(today, -1), "yyyy-MM-dd"),
    weightKg: 68,
    heightCm: 164,
    bmi: calculateBmi(68, 164),
    goal: "Weight Loss",
    warmupExercises: "Dynamic leg swings, treadmill walk",
    flexibilityTraining: "Hamstring and hip flexor stretch",
    cardioTraining: "Bike intervals 18 minutes",
    planType: "1 Month",
    membershipStart: format(addMonths(today, -1), "yyyy-MM-dd"),
    membershipDue: format(addDays(today, -2), "yyyy-MM-dd"),
    feesAmount: 1800,
    paymentStatus: "Pending",
    status: "Expired",
    smsSent3days: true,
    trainingType: "General",
    address: "",
    partialPaidAmount: 0,
    balanceAmount: 1800,
    createdAt: addMonths(today, -1).toISOString(),
    updatedAt: today.toISOString(),
  },
  {
    id: "member-003",
    regNo: "FW-003",
    name: "Mohan Raj",
    phone: "9988776655",
    age: 41,
    gender: "Male",
    joinDate: format(addMonths(today, -8), "yyyy-MM-dd"),
    weightKg: 74,
    heightCm: 171,
    bmi: calculateBmi(74, 171),
    goal: "General Fitness",
    healthProblem: "No current issues",
    specialInstruction: "Prefers morning sessions",
    warmupExercises: "Rowing machine, mobility flow",
    flexibilityTraining: "Full body cooldown",
    cardioTraining: "Cross trainer 15 minutes",
    planType: "6 Months",
    membershipStart: format(addMonths(today, -1), "yyyy-MM-dd"),
    membershipDue: format(addMonths(today, 5), "yyyy-MM-dd"),
    feesAmount: 7800,
    paymentStatus: "Paid",
    status: "Active",
    smsSent3days: false,
    trainingType: "General",
    address: "",
    partialPaidAmount: 7800,
    balanceAmount: 0,
    createdAt: addMonths(today, -8).toISOString(),
    updatedAt: today.toISOString(),
  },
  {
    id: "member-004",
    regNo: "FW-004",
    name: "Nisha Varun",
    phone: "9090909090",
    age: 24,
    gender: "Female",
    joinDate: format(addMonths(today, -3), "yyyy-MM-dd"),
    weightKg: 55,
    heightCm: 159,
    bmi: calculateBmi(55, 159),
    goal: "Weight Gain",
    goalOther: "",
    warmupExercises: "Light cardio and activation",
    flexibilityTraining: "Lower-body stretches",
    cardioTraining: "Low intensity 8 minutes",
    planType: "3 Months",
    membershipStart: format(addMonths(today, -1), "yyyy-MM-dd"),
    membershipDue: format(addDays(today, 12), "yyyy-MM-dd"),
    feesAmount: 4500,
    paymentStatus: "Pending",
    status: "Active",
    smsSent3days: false,
    trainingType: "General",
    address: "",
    partialPaidAmount: 0,
    balanceAmount: 4500,
    createdAt: addMonths(today, -3).toISOString(),
    updatedAt: today.toISOString(),
  },
];

export const sampleAttendance: AttendanceEntry[] = [
  {
    id: "visit-001",
    memberId: "member-001",
    visitDate: format(addDays(today, -1), "yyyy-MM-dd"),
    weightKg: 82,
    createdAt: addDays(today, -1).toISOString(),
  },
  {
    id: "visit-002",
    memberId: "member-001",
    visitDate: format(addDays(today, -5), "yyyy-MM-dd"),
    weightKg: 82.4,
    createdAt: addDays(today, -5).toISOString(),
  },
  {
    id: "visit-003",
    memberId: "member-003",
    visitDate: format(addDays(today, -2), "yyyy-MM-dd"),
    weightKg: 74,
    createdAt: addDays(today, -2).toISOString(),
  },
];
